name: CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  prep:
    runs-on: ubuntu-latest
    name: 'Prepare'
    outputs:
      did_tasks: ${{ steps.tasks.conclusion }}
      did_license: ${{ steps.license.conclusion }}
      did_test: ${{ steps.test.conclusion }}
      did_build: ${{ steps.build.conclusion }}
    steps:
    - id: tasks
    - uses: actions/checkout@v2
    - name: 'Setup'
      run: './gradlew tasks'
    - name: 'Check License'
      run: './gradlew checkLicense'
    - name: 'Test'
      run: './gradlew test'
    - name: 'Build'
      run: './gradlew build'
  output_tasks:
    runs-on: ubuntu-latest
    needs: prep
    steps:
    - name: 'Check Tasks'
      run: |
        echo "${{ needs.prep.outputs.did_tasks }}"
        if [[ ${{ needs.prep.outputs.did_tasks }} -eq ]]; then; exit 1; fi
