name: CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  prep:
    runs-on: ubuntu-latest
    name: 'Prepare'
    outputs:
      did_tasks: ${{ steps.tasks.conclusion }}
      did_license: ${{ steps.license.conclusion }}
      did_test: ${{ steps.test.conclusion }}
      did_build: ${{ steps.build.conclusion }}
    steps:
    - uses: actions/checkout@v2
    - id: tasks
      name: 'Setup'
      run: |
       ./gradlew tasks
       not_a_real_command
    - id: 'license'
      name: 'Check License'
      run: './gradlew checkLicense'
    - id: 'test'
      name: 'Test'
      run: './gradlew test'
    - id: 'build'
      name: 'Build'
      run: './gradlew build'
  output_tasks:
    runs-on: ubuntu-latest
    needs: prep
    steps:
    - name: 'Check Tasks'
      run: |
        echo "${{ needs.prep.outputs.did_tasks }}"
        if [[ ${{ needs.prep.outputs.did_tasks }} != "success" ]]; then
        exit 1
        fi
