name: CI

on:
  push:
  pull_request:
    branches: '**:**'

jobs:
  prep:
    runs-on: ubuntu-latest
    name: 'Prepare'
    outputs:
      did_tasks: ${{ steps.tasks.conclusion }}
      did_license: ${{ steps.license.conclusion }}
      did_test: ${{ steps.test.conclusion }}
      did_build: ${{ steps.build.conclusion }}
    steps:
    - uses: actions/checkout@v2
    - id: tasks
      name: 'Setup'
      run: './gradlew tasks'
    - id: 'license'
      name: 'Check License'
      run: './gradlew checkLicense'
    - id: 'test'
      name: 'Test'
      run: './gradlew test'
    - id: 'build'
      name: 'Build'
      run: './gradlew build'
  output_tasks:
    runs-on: ubuntu-latest
    needs: prep
    if: always()
    steps:
    - name: 'Check Tasks'
      run: |
        echo "${{ needs.prep.outputs.did_tasks }}"
        if [[ ${{ needs.prep.outputs.did_tasks }} != "success" ]]; then
        exit 1
        fi
  output_license:
    runs-on: ubuntu-latest
    needs: prep
    if: always()
    steps:
    - name: 'Check License'
      run: |
        echo "${{ needs.prep.outputs.did_license }}"
        if [[ ${{ needs.prep.outputs.did_license }} != "success" ]]; then
        exit 1
        fi
  output_test:
    runs-on: ubuntu-latest
    needs: prep
    if: always()
    steps:
    - name: 'Check Test'
      run: |
        echo "${{ needs.prep.outputs.did_test }}"
        if [[ ${{ needs.prep.outputs.did_test }} != "success" ]]; then
        exit 1
        fi
  output_build:
    runs-on: ubuntu-latest
    needs: prep
    if: always()
    steps:
    - name: 'Check Build'
      run: |
        echo "${{ needs.prep.outputs.did_build }}"
        if [[ ${{ needs.prep.outputs.did_build }} != "success" ]]; then
        exit 1
        fi
