# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the 0.4.x-1.16.x branch
on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_license:
    runs-on: ubuntu-latest
    name: 'Check License'
    steps:
    - uses: actions/checkout@v2
    - name: '(Actually check the license)'
      run: './gradlew checkLicense'
      
  test:
    runs-on: ubuntu-latest
    name: 'Test'
    steps:
      - uses: actions/checkout@v2
      - name: '(run)'
        run: './gradlew test'
  build:
    runs-on: ubuntu-latest
    name: 'Build'
    steps:
      - uses: actions/checkout@v2
      - name: '(run)'
        run: './gradlew build'
